### ISSUE TITLE
Custom userId and tags

### ISSUE THREAD

**Issue by minahmoghadam** [jadengis/ngx-clarity#4]
Hi.
Is there any way to set userId in Clarity from this package?

**Comment by faraz-ahmad-uft** [comment]
@minahmoghadam - Could you find a way to do this? I have similar requirements in my project.

**Comment by jadengis** [comment]
@minahmoghadam Hi Mina? Can you link me to documentation about the userId? Currently there is no way to add userId but it could be added fairly easily I'm certain.

**Comment by jadengis** [comment]
@minahmoghadam [Is this what you are referring to](https://learn.microsoft.com/en-us/clarity/setup-and-installation/clarity-api#customize-your-identifiers)? Technically, these APIs will work today because what this library does is just inject the clarity script during app initialization, so after initialization the `clarity` function will be available.

If you are looking for a more __Angular__ solution, I wouldn't be opposed to a service that wraps the clarity function for more idiomatic code. Let me know if this is what you are looking for.

**Comment by jadengis** [comment]
@minahmoghadam @faraz-ahmad-uft Do you still require help with this issue? Otherewise I'm going to close it.

**Comment by faraz-ahmad-uft** [comment]
You can close it for now
